### ISSUE TITLE
Looking for stock firmware for the TrekStor® SurfTab® breeze 10.1 quad plus (ST10408-11)

### ISSUE THREAD

**Issue by Heinz-Beans** [schrmh/AndroidDevices#1]
I have stumbled upon this android tablet and the tablet is in a state where there is wrong firmware flashed onto it. 
It has been flashed with firmware version for SurfTab breeze 10.1 quad (non PLUS version) and doesn't work.
Backup for the previous correct firmware does not exist.

Is there a chance you could have a backup of your old firmware somewhere for this device, that you would be wiling to share ?

**Comment by schrmh** [comment]
@ImTheBadWolf If you got this exact device "SurfTab breeze 10.1 quad plus" then tell me which partitions you need (in case you tried to flash a specific partition and its not working afterwards) and I will take a quick look and might decide to share it online.
Or if you can come to Baden-Württemberg (southwest Germany) then I will flash my backup that contains personal information and remove that information afterwards (due to time constraints I don't really want to factory reset my device, take a backup without personal data and then reflash it again).

In case you got the non-plus version:
 https://www.android-hilfe.de/forum/trekstor-allgemein.1721/surftab-breeze-10-1.637022-page-5.html#post-10019526  
The person there reported that it worked with this backup. I also have a local copy of that in case the link goes down.  
Btw. spflashtool 6 looks (and works?) quite different from spflashtool 5. If you have problems, try the older version.
Here is the scatter file for that device:  
[MT8127_Android_scatter_surftab_quad_101.txt](https://github.com/schrmh/AndroidDevices/files/10559454/MT8127_Android_scatter_surftab_quad_101.txt)

**Comment by Heinz-Beans** [comment]
@schrmh I have the plus version. ( "SurfTab breeze 10.1 quad plus"). I would need every partition probably. The tablet has wrong firmware flashed so I would need to re-flash everything. 
Coming to Germany to flash the tablet is not really feasible for me :D and I understand that you don't want to share your backup with personal information, so I will try looking for the stock firmware somewhere else and hope that I can find it.

**Comment by schrmh** [comment]
@ImTheBadWolf You could try:
https://gsmexpertzone.com/index.php?a=downloads&b=file&id=31230
However this site needs a phone number to register and thus I never tried to register and download that.
But the description looks kinda valid (I looked at my personal copy of this repo which contains a logs folder with device logs in which ro.mediatek.version.release=ALPS.L1.MP8.V2_HTT8127.TB.L1 appears. Surprised it is not in any of the public files I shared in this repo so I guess I might try to get this string at a later date via adb and upload a file containing that)

Btw. it may be the case that this backup, if it is actually downloadable, only works with this Miraclebox thing which is sadly paid (and some require hardware?) but there are cracked software versions.

**Edit: Site may be a scam tbh.**

**Comment by Heinz-Beans** [comment]
Yeah site looks like a scam. But I registered nevertheless and tried to download that file only to find out that in order to download I must pay 15$ first ... :D

**Comment by schrmh** [comment]
Eh, why did you close that issue then? Did you actually pay that (I tried to login after registering with fake data but I got a "Dfp is required" error so I wasn't even able to see the costs lol)?

**Comment by Heinz-Beans** [comment]
I closed it by accident... I got the same "Dfp" error but it went away after I turned off adblock, so maybe try that.
But you will get this message after trying to download 
![image](https://user-images.githubusercontent.com/28805769/216282098-f1bd5610-eec8-4439-a518-9992090b8a6d.png)
And the package that allows downloading feature files costs 15$.

**Comment by schrmh** [comment]
@ImTheBadWolf I will format my device now and then take a backup...
Yesterday I took a backup of the partitions containing data I want to keep so yeah...

Can't stand broken devices and I was able to get some time now

**Comment by schrmh** [comment]
@ImTheBadWolf 
**Edit: Ignore this:**
You know what is funny: I just opened my device to try to fix a small hardware issue (volume keys not working; turns out plastic was not pressing the right spot) and after that I searched for flex cable numbers.
Turns out our small device has an almost identical clone (MULTIPAD WIZE 5002 or PMT5002_WI_C_BK) sold under a different company (Prestigio).
And the funny part is: They offer a firmware file download (for free and without login ofc):
https://prestigio.com/archive-products/multipads-archive/multipad-wize-5002

Would be cool if you could try this first (however, maybe still take a backup of the broken state you have first... just in case Prestigio has a different layout), I will then upload my backup later in case it is still needed

**EDIT: There is a scatter.txt inside and it is different!** (More close to the non plus variant of this tablet, until including partition 19)

**Comment by Heinz-Beans** [comment]
@schrmh Thank you for your time. Please upload your backup if you can.
I will maybe try that prestigio firmware and hope I dont brick it :D

**Comment by schrmh** [comment]
Yeah, the reason I'm looking first for those alternatives is that I also want to find a company from which we not only get a good working firmware packing from but that I can ask for kernel sources thus that we could not only unbrick a bunch of devices of people of different brands that sold effectively the same hardware but to also establish a small development community to bring something better than Android 5 to these devices.   

**Would tar.lrz be okay for you (archive compressed by lrzip to achieve maximum compresson)? Cause I guess I would upload it to a personal Mega.nz account (feel free to suggest an alternative) and the backup is 7.1 GB uncompressed (for that size with 10 Mbit/s upload it would mean a bit more than 1,5h upload time in the best case).**

There were also the Mecer 101p51c which is one device pretty close to one of these devices (but not the plus version)
Found another device: Crypto Creev Q1000.
Another one that is similar (but has HDMI port): VIVAX TPC-10100

**Comment by Heinz-Beans** [comment]
Lrz is fine by me.

**Comment by schrmh** [comment]
@ImTheBadWolf Here you go (@android-hilfe.de readers: it's only for the plus version): https://send.zcyph.cc/download/3d5fca298cf54f2f/#pNA_Ndk2APKI-2UF9qkvHQ
(edit at first of october 2023: link is dead, earlier than it should be. Will reupload after somebody asks for it)
Download it from the website or by using `ffsend download`. Link is valid for one year.
Please report back if the backup works for you. If it does, I will look if Android File Host or some firmware site is an option for a more permanent storage solution.

The ~700M .tar.lrz archive has an md5sum of _3cc4c20cdebec95986f1ec19d1da3165_.  
You can extract it to a 7.1G .tar by using the `lrunzip` command (you need at least 3 GB of RAM for this; process took two hours on my Ryzen 7 3700X machine. It will likely take longer on less powerful systems. The second precentage increases in steps of 10 so it will stay at the same percentage for some time).  
The .tar can be extracted by using `tar -xf`.  

README text file might contain some useful things in case you have problems.  
Consider joining these Matrix spaces:
Specific device space: https://matrix.to/#/#trekstor-surftab-breeze-101-quad-plus:matrix.org
General AndroidDevices space: https://matrix.to/#/#androiddevices:matrix.org

**Comment by Heinz-Beans** [comment]
Thank you very much ! I will try to install it later today/tomorrow.

**Comment by schrmh** [comment]
Ah, cause I see it now in Chromium which doesn't let me downlod it myself:
Use Firefox (or the ffsend tool) in case the download doesn't work (Firefox Send was originally a Mozilla project and it looks like Chromium is missing something for it to work).
